USERNAME: 'cull0084'
ASSEMBLY:
    NCBI: 'GCF_002863925.1_EquCab3.0'
    ENSEMBL: 'Equus_caballus.EquCab3.0'
BUCKET: 
    PRIVATE: 'HorseGeneAnnotation/private/sequence/RNASEQ/bam'
    PUBLIC: 'HorseGeneAnnotation/public/refgen'
THREADS:
    SALMON: 4
