#!/bin/bash                                         

set -e

samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/1_M_S120.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/1_M_S120.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/12_F_S132.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/12_F_S132.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/17_M_S121.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/17_M_S121.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/20_M_S122.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/20_M_S122.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/35_F_S133.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/35_F_S133.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/35_M_S124.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/35_M_S124.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/36_F_S134.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/36_F_S134.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/37_M_S125.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/37_M_S125.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/39_F_S135.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/39_F_S135.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/39_M_S126.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/39_M_S126.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/40_M_S89.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/40_M_S89.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/49_M_S82.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/49_M_S82.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/51_F_S140.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/51_F_S140.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/52_M_S127.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/52_M_S127.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/61_M_S128.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/61_M_S128.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/65_F_S141.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/65_F_S141.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/65_M_S129.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/65_M_S129.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/66_F_S136.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/66_F_S136.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/66_M_S130.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/66_M_S130.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/67_F_S142.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/67_F_S142.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/67_M_S131.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/67_M_S131.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/69_F_S137.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/69_F_S137.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/82_M_S36.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/82_M_S36.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/86_M_S14.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/86_M_S14.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/87_M_S41.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/87_M_S41.sorted.bam
samtools merge HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/merged/90_M_S88.merged.sorted.bam HorseGeneAnnotation/private/sequence/RNASEQ/bam/Equus_caballus.EquCab3.0.95/paired_end/novaseq/STAR/90_M_S88.sorted.bam
